# Generated by Django 5.2.1 on 2025-06-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="recipients",
            field=models.ManyToManyField(
                blank=True,
                related_name="campaigns",
                to="app.recipient",
                verbose_name="Клиенты",
            ),
        ),
    ]
