# Generated by Django 5.2.1 on 2025-06-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_campaign_is_active_alter_campaign_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipient",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
        migrations.AddField(
            model_name="recipient",
            name="country",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="recipient",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
