# Generated by Django 5.2.1 on 2025-06-04 15:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_recipient_avatar_recipient_country_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="campaign",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(fields=["status"], name="app_campaig_status_270b04_idx"),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(fields=["owner"], name="app_campaig_owner_i_f4324b_idx"),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["is_active"], name="app_campaig_is_acti_f7a627_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["start_time"], name="app_campaig_start_t_3262a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["end_time"], name="app_campaig_end_tim_6bef4a_idx"
            ),
        ),
    ]
